spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/djonko/config-server.git
          clone-on-start: true
          default-label: main
          basedir: configFile
server:
  port: 9296
eureka:
  instance:
    hostname: eureka-0.eureka
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka