apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-gateway-app
  labels:
    app: cloud-gateway-app
spec:
  replicas: 1
  template:
    metadata:
      name: cloud-gateway-app
      labels:
        app: cloud-gateway-app
    spec:
      containers:
        - name: cloud-gateway-app
          image: djonko/dailycodebuffer_cloud-gateway:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9191
      restartPolicy: Always
  selector:
    matchLabels:
      app: cloud-gateway-app

---
apiVersion: v1
kind: Service
metadata:
  name: cloud-gateway-svc
spec:
  selector:
    app: cloud-gateway-app
  ports:
    - port: 80
      targetPort: 9191
      protocol: TCP
  type: LoadBalancer
