apiVersion: v1
kind: Service
metadata:
  name: config-server-app
  labels:
    app: config-server-app
spec:
  clusterIP: None
  ports:
    - port: 9296
      name: config-server-app
  selector:
    app: config-server-app
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: config-server-app
spec:
  serviceName: "config-server-app"
  replicas: 1
  selector:
    matchLabels:
      app: config-server-app
  template:
    metadata:
      labels:
        app: config-server-app
    spec:
      containers:
        - name: config-server-app
          image: djonko/dailycodebuffer_cloud-config-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9296
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: config-server-app-lb
  labels:
    app: config-server-app
spec:
  selector:
    app: config-server-app
  type: NodePort
  ports:
    - port: 80
      targetPort: 9296
      nodePort: 30036
