apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server-app
  labels:
    app: config-server-app
spec:
  replicas: 1
  template:
    metadata:
      name: config-server-app
      labels:
        app: config-server-app
    spec:
      containers:
        - name: config-server-app
          image: djonko/dailycodebuffer_cloud-config-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9296
          #env:
            #- name: _JAVA_OPTIONS
              #value: -Deureka.instance.preferIpAddress=true -Deureka.client.serviceUrl.defaultZone=http://eureka-0.eureka:8761/eureka/
      restartPolicy: Always
  selector:
    matchLabels:
      app: config-server-app

---
apiVersion: v1
kind: Service
metadata:
  name: config-server-svc
spec:
  selector:
    app: config-server-app
  ports:
    - port: 80
      targetPort: 9296