apiVersion: v1
kind: Service
metadata:
  name: zipkin-server
  labels:
    app: zipkin-server
spec:
  clusterIP: None
  ports:
    - port: 9411
      name: zipkin-server
  selector:
    app: zipkin-server
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zipkin-server
spec:
  serviceName: "zipkin-server"
  replicas: 1
  selector:
    matchLabels:
      app: zipkin-server
  template:
    metadata:
      labels:
        app: zipkin-server
    spec:
      containers:
        - name: zipkin-server
          image: openzipkin/zipkin:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9411
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: zipkin-server-lb
  labels:
    app: zipkin-server
spec:
  selector:
    app: zipkin-server
  type: NodePort
  ports:
    - port: 80
      targetPort: 9411
